[package]
name = "zpgsa_pdf_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rayon = "1.10.0"
regex = "1.11.1"
tokio = { version = "1.45.1", features = ["full"] }
reqwest = "0.12.20"
kuchiki = "0.8.1"
futures = "0.3.31"
pdf-extract = "0.9.0"