[package]
name = "zpgsa_pdf_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rayon = "1.10.0"
which = "8.0.0"